# Generated by Django 5.2.15 on 2026-07-21 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(default='BRG-000', max_length=10, unique=True, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('merk', models.CharField(default='Umum', max_length=100)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('harga_sewa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Sangat Baik', 'Sangat Baik'), ('Rusak', 'Rusak')], default='Baik', max_length=20)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='barang/')),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tidak Tersedia', 'Tidak Tersedia')], default='Tersedia', max_length=20)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='penyewaan.kategori')),
            ],
            options={
                'ordering': ['kode_barang'],
            },
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_acara', models.CharField(max_length=150)),
                ('tanggal_sewa', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('lokasi', models.TextField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('total_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_transaksi', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Ditolak', 'Ditolak'), ('Disetujui', 'Disetujui'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Lunas', 'Lunas'), ('Sedang Disewa', 'Sedang Disewa'), ('Selesai', 'Selesai')], default='Menunggu Persetujuan', max_length=30)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='bukti_tf/')),
                ('kondisi_kembali', models.CharField(blank=True, max_length=30, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penyewaan.barang')),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('status_akun', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Aktif', 'Aktif'), ('Ditolak', 'Ditolak')], default='Menunggu Persetujuan', max_length=25)),
                ('role', models.CharField(choices=[('Petugas', 'Petugas'), ('Penyewa', 'Penyewa')], default='Penyewa', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
