# Generated by Django 5.2.15 on 2026-07-20 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='barang/')),
                ('stok', models.IntegerField()),
                ('harga_hari', models.IntegerField()),
                ('status', models.CharField(default='Tersedia', max_length=20)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penyewaan.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_acara', models.CharField(max_length=150)),
                ('tanggal_sewa', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('lokasi', models.TextField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('total_harga', models.IntegerField(blank=True, null=True)),
                ('status_transaksi', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Ditolak', 'Ditolak'), ('Disetujui', 'Disetujui'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Lunas', 'Lunas'), ('Sedang Disewa', 'Sedang Disewa'), ('Selesai', 'Selesai')], default='Menunggu Persetujuan', max_length=30)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='bukti_tf/')),
                ('kondisi_kembali', models.CharField(blank=True, max_length=30, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penyewaan.barang')),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilPengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('status_akun', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Aktif', 'Aktif'), ('Ditolak', 'Ditolak')], default='Menunggu Persetujuan', max_length=25)),
                ('role', models.CharField(choices=[('Petugas', 'Petugas'), ('Penyewa', 'Penyewa')], default='Penyewa', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
