# Generated by Django 6.0.6 on 2026-07-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyewaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipinjam', 'Dipinjam')], default='Tersedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilpengguna',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Operator', 'Operator'), ('Dosen', 'Dosen')], default='Dosen', max_length=20),
        ),
    ]
