# Generated by Django 6.0.6 on 2026-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyewaan', '0002_alter_barang_status_alter_profilpengguna_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Denda Keterlambatan', max_length=100)),
                ('biaya_per_hari', models.IntegerField()),
            ],
        ),
    ]
